### ISSUE TITLE
where is io.h and linked-list.h?

### ISSUE THREAD

**Issue by zhanchi-fork** [HQarroum/packet-sniffer#1]

**Comment by HQarroum** [comment]
Hey,

Thanks for your interest.

`io.h` and the `io.c` implementation were indeed missing, I've just added them. I've used the [circular-linked-list](https://github.com/HQarroum/circular-linked-list) library to build this tool. It is on my TODO list to integrate properly dependencies using Cmake or even biicode.

In the mean time, you can still clone [circular-linked-list](https://github.com/HQarroum/circular-linked-list) as a submodule in the `sniffy` directory and build it separately.
